version: '2'     
services:

    backend:
        build: ./server            

        ports:
        - "127.0.0.1:4000:4000"

    frontend:
        build: ./client

        ports:
        - "80:3000"             

        depends_on:
        - backend

        stdin_open: true